config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :users 
  resource :session, only:[:new, :create, :destroy]

  get '/account_details' => 'users#edit'
  get '/change_password', to: 'users#change_password', as: :change_password
  post '/update_password', to: 'users#update_password', as: :update_password

end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password
    has_many :posts, dependent: :nullify
    has_many :comments, dependent: :nullify
    validates(:name, presence: true)
    validates(:email, presence: true, uniqueness: true, format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i)
        
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # =============CALLBACKS=====================
  before_action :find_user, only: [:update]  
  before_action :authenticated_user!, only: [:update, :edit]

 # ==============CREATE========================
 def new
       @user = User.new
 end
   
   def create
       @user = User.new user_params

       if @user.save
         session[:user_id] = @user.id
         flash.notice = "Signed up!"
         redirect_to root_path
       else
         render :new, status: 303
       end 
   
   end

   # ===============UPDATE==========================
   def edit
    @user = User.find_by_id current_user.id
   end

   def update
    if @user.update user_params
      redirect_to root_path
      flash.notice = "Account updated successfully!"
      else
         render :edit
         flash.notice = "Error!"
       end
   end
 
   def change_password 
    @user = User.find_by_id current_user.id
   end
 
   def update_password  
    @user = User.find_by_id current_user.id

    @current_password = params[:current_password]
    @new_password = params[:new_password]
    @new_password_confirmation = params[:new_password_confirmation]

    if @user && @user.authenticate(@current_password)

      if @current_password != @new_password && @new_password == @new_password_confirmation
        if @user.update password: @new_password
          flash.alert = 'Password has been updated successfully'
          redirect_to root_path
        end
      elsif @current_password == @new_password
          flash.alert = 'New password has to be different'
          render :change_password, status: 303
      elsif @current_password != @new_password && @new_password != @new_password_confirmation
          flash.alert = 'New passwords do not match'
          render :change_password, status: 303
      end

    else
      flash.alert = 'Error! Please try again!'
      render :change_password, status: 303
    end

  end


 private

 def find_user
   @user = User.find_by_id params[:id]
 end

 def user_params
   params.require(:user).permit(:name, :email, :password, :password_confirmation)
 end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/change_password.html.erb
<div class="container d-flex justify-content-center">
<div class="col-sm-6 m-4">
<h1>Change Password</h1>

<% if @user.errors && @user.errors.any? %>
  <p><%= @user.errors.full_messages.join(', ') %> </p>
<% end %>

<%= form_with url: update_password_path do |f| %>
  <div class="form-group">
    <%= f.label :current_password %>
    <%= f.password_field :current_password, class:"form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :new_password %>
    <%= f.password_field :new_password, class:"form-control", required: true, minlength:"3", maxlength:"12" %>
  </div>
  <div class="form-group">
    <%= f.label :new_password_confirmation %>
    <%= f.password_field :new_password_confirmation, class:"form-control", required: true, minlength:"3", maxlength:"12" %>
  </div> 

  <br>
  <%= f.submit "Change Password", class:"btn btn-outline-primary" %>
<% end %>

</div>
</div>

app/views/users/edit.erb
<div class="container d-flex justify-content-center">
<div class="col-sm-6 m-4">
<h1>Account Details</h1>

  <div class="form">
  <% if @user.errors.any? %>
  <p><%= @user.errors.full_messages.join(', ') %> </p>
<% end %>

<%= form_with(model: @user) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:"form-control" %>
  </div>
  <br>
  <%= f.submit "Update Account", class: "btn btn-outline-primary" %>
<% end %>
 <br>

 <a class="btn btn-primary" href="<%= change_password_path %>">Change Password</a>

</div>
</div>

app/views/users/edit.html.erb
<div class="container d-flex justify-content-center">
<div class="col-sm-6 m-4">
<h1>Account Details</h1>

  <div class="form">
  <% if @user.errors.any? %>
  <p><%= @user.errors.full_messages.join(', ') %> </p>
<% end %>

<%= form_with(model: @user) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:"form-control" %>
  </div>
  <br>
  <%= f.submit "Update Account", class: "btn btn-outline-primary" %>
<% end %>
 <br>

 <a class="btn btn-primary" href="<%= change_password_path %>">Change Password</a>

</div>
</div>

app/views/users/new.html.erb
<div class="container d-flex justify-content-center">
<div class="col-sm-6 m-4">
<h1>Sign Up</h1>
<div class="form">
<% if @user.errors.any? %>
  <p><%= @user.errors.full_messages.join(', ') %> </p>
<% end %>
<%= form_with model: @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email, class:"form-control" %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password, class:"form-control" %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:"form-control" %>
  </div>
  <br>
  <%= f.submit "Sign up", class: "btn btn-outline-primary" %>
<% end %>
</div>
</div>
</div>