config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :users 
  resource :session, only:[:new, :create, :destroy]

  get '/account_details' => 'users#edit'
  get '/change_password', to: 'users#change_password', as: :change_password
  post '/update_password', to: 'users#update_password', as: :update_password

end

app/models/post.rb
class Post < ApplicationRecord

    has_many :comments, dependent: :destroy

    belongs_to :user
    
    validates :title, presence: { message: "must be provided" }, uniqueness: true 
    validates :body, presence: { message: "must be at least 50 characters" }, length: {minimum: 50}

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    # =============CALLBACKS=====================
    before_action :find_post, only: [:edit, :update, :show, :destroy]
    before_action :authenticated_user!, except: [:index, :show]
    before_action :authorize_user!, only:[:edit, :update, :destroy]
    # ==============CREATE========================
    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user = current_user
        if @post.save
            flash[:notice]= "Post created successfully!"
            redirect_to post_path(@post)
        else
            # flash[:alert]= "Title must be unique and body must has at least 50 characters"
            render :new, status: 303  
        end
       
        
    end
    # ================READ========================
    def index
        @posts = Post.order(created_at: :desc)
    end

    def show
        @comments = @post.comments.order(created_at: :desc)
        @comment = Comment.new
    end
    # ===============UPDATE==========================
    def edit
    end

    def update
        if @post.update(post_params)
            redirect_to post_path(@post)
          else
            render :edit
          end
    end
    # ================DELETE=========================
    def destroy
        @post.destroy
        redirect_to posts_path
    end

    private

    def authorize_user!
        redirect_to root_path, alert: "Not authorized" unless can?(:crud, @post)
      end

    def find_post
        @post = Post.find params[:id]
    end

    def post_params
        params.require(:post).permit(:title, :body)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: @post) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :body %>
    <br>
    <%= form.text_area :body, cols:50, rows: 5, class: "form-control"%>
  </div>

app/views/posts/edit.html.erb
<div class="container">

<%= form_with(model: @post) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :body %>
    <br>
    <%= form.text_area :body, cols:50, rows: 5, class: "form-control"%>
  </div>
<br>

<%= form.submit "Update Post", class: "btn btn-outline-primary" %>
<% end %>
</div>

app/views/posts/index.html.erb
<div class="container">
<div class="container d-flex flex-wrap justify-content-around">
<% @posts.each do |post| %>
  <div class="card" style="width: 20rem; height: 15em; margin: 1em">
  <div class="card-body">
    <h5 class="card-title"><%= link_to post.title, post_path(post), class: "text-decoration-none" %></h5>
    <p class="card-text"><%=post.body.first(50)%>...</p>
  </div>
</div>
<br>
<% end %>
</div>
</div>

app/views/posts/new.html.erb
<div class="container d-flex justify-content-center">
<div class="col-sm-6 m-4">
<%= form_with(model: @post) do |form| %>
<% if @post.errors.any? %>
  <p><%= @post.errors.full_messages.join(', ') %> </p>
<% end %>
  <div class="form-group">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :body %>
    <br>
    <%= form.text_area :body, cols:50, rows: 5, class: "form-control"%>
  </div>
<br>

  <%= form.submit "Create Post", class: "btn btn-outline-primary" %>
 <% end %>
</div>
</div>

app/views/posts/show.html.erb
<div class="container d-flex justify-content-center">
<div class="col-sm-6 m-4">
<div class="container" style="margin: 1em">
  <h1><%= @post.title %></h2>
  <p><%= @post.body %></p>
  <small>Posted <%= time_ago_in_words(@post.created_at) %> ago</small><br>
  <small>Created by: <%= @post.user.name %></small>
  <br><br>

  <%# Edit and Delete Buttons %>
  <% if can? :crud, @post %>
  <div class="btn-group">
  <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-outline-primary", style:"margin-right: 0.5em" %>
  </br>
  <%= button_to 'Delete', post_path(@post), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "btn btn-outline-primary"  %>  
  </div>
  <% end %>
</div>


<div class="container" style="margin: 1em">
<h3 >Comment</h3>

<% if @comment.errors.any? %>
  <ul>
    <%  @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model:[@post, @comment]) do |f| %>
  <div class="form-group">
    <%= f.text_area :body, cols: 50, rows: 2, placeholder: "What's on your mind?", class:"form-control", style:"width: 25em" %>
  </div>
  <br>
  <%= f.submit "Submit", class: "btn btn-outline-primary" %>
<% end %>
</div>
<div class="container" style="margin: 1em">
<% @comments.each do |comment| %>
  <div class="mb-3">
    <%= comment.body %><br>
    
    <span style="display: flex; flex-direction: row; align-items: baseline"><small>Commented <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user.name %></small>
    <%# Delete Button %>
    <% if can? :crud, comment %>
    <span><%= button_to "Delete", post_comment_path(@post, comment), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "btn btn-link", style:"text-decoration: none; box-shadow:none; padding: 0 0 0 0.32em" %></span></span>
    <% else %>
    <br>
    <% end %>
    
  </div>
<% end %>
</div>

</div>
</div>